version: "3.7"

volumes:
  db-data:

networks:  
  instavote:
    driver: bridge        

services:  
  vote:
    image: kavsjo/vote:latest
    ports:
      - 5000:80
    depends_on:
      - redis      
    networks:
      - instavote

  redis:      
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:13.0
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote

  result:
    image: kavsjo/result:latest
    ports:
      - 5001:4000
    depends_on:
      - db       
    networks:
      - instavote 

  worker:
    image: kavsjo/worker:latest
    depends_on:
      - redis
      - db
    networks:
      - instavote